# Generated by Django 3.2 on 2021-06-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('answer_a', models.CharField(max_length=60, verbose_name='Вариант А')),
                ('answer_b', models.CharField(max_length=60, verbose_name='Вариант Б')),
                ('answer_c', models.CharField(max_length=60, verbose_name='Вариант В')),
                ('answer_d', models.CharField(max_length=60, verbose_name='Вариант Г')),
                ('right_answer', models.CharField(max_length=5, verbose_name='Правильный вариант')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True, verbose_name='Ник')),
                ('choices', models.TextField(verbose_name='Ответы')),
            ],
        ),
    ]
