# Generated by Django 3.2 on 2021-06-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='choices',
        ),
        migrations.AddField(
            model_name='user',
            name='choice',
            field=models.TextField(default=1, verbose_name='Ответы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_question',
            field=models.IntegerField(default=1, verbose_name='Номер вопроса'),
            preserve_default=False,
        ),
    ]
