# Generated by Django 3.2 on 2021-06-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210611_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='radio',
            field=models.BooleanField(default=1, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
