# Generated by Django 3.2 on 2021-06-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_question_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='finish',
            field=models.IntegerField(default=-1, verbose_name='Какой процент выполнен'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_a',
            field=models.CharField(max_length=30, verbose_name='Вариант А'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_b',
            field=models.CharField(max_length=30, verbose_name='Вариант Б'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_c',
            field=models.CharField(max_length=30, verbose_name='Вариант В'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_d',
            field=models.CharField(max_length=30, verbose_name='Вариант Г'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=50, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='radio',
            field=models.BooleanField(verbose_name='Один вариант ответа'),
        ),
    ]
